src/flow_tracker.rs
src/process_packet.rs
src/util.rs

This PR adds the ability for the detector to look for special UDP packets sent as DNS requests for a certain domain, used for routing research. The detector only examines UDP packets sent to port 53, and only does any comparisons if the UDP payload is at least `SPECIAL_UDP_PAYLOAD.len()` bytes long (`windows` will return an iterator with no values otherwise), which is rare for a DNS packet. While it would have been possible to bring in a DNS parsing library as well, given that our packets are abnormal enough to scrap most DNS packets before doing any parsing and most slice comparisons will return early after the first byte not matching, I felt like it was simpler to just look for the payload in the UDP payload itself.

Add checks for UDP probe packets

---

.github/workflows/build.yml

Building on each station server individually duplicates a lot of work that can be streamlined
Add CI pipeline to build the station here and upload artifacts to be used once pulled. This simplifies the process of deploying stations each time we change the station code and patch issues.  With this model stations need significantly fewer elements installed and can more easily manage their configurations.
ubuntu-18.04
go-1.15.4
rust-latest
pf_ring 7.2.0-stable

Added build CI pipeline action

---

src/flow_tracker.rs
src/process_packet.rs

IPv6 addresses are printed incorrectly by the station logging system. This breaks parsing and interpretation later down the road. 
logging involving  a flow with address 2601::1 and port 443 looks like  
```
2601::1:443 -> ...
[2601::1]:443 -> ...
```
To correct this I have updated the `impl fmt::Display` for the struct to use the rust `SocketAddr` system which does automatic formatting generic across IPv4 and IPv6.  I added a test to confim that the formatting was what we expected it to be.

Update Flow log format

---

application/config.toml
application/lib/config.go
application/lib/config_test.go
application/main.go
application/registration_with_transport_test.go
src/c_api.rs
src/flow_tracker.rs
src/process_packet.rs

Registrations are currently allowed which redirect traffic to any address as a covert target. This allows users to connect to dangerous addresses like `127.0.0.1`, `10.0.0.0/8`,  etc.
This PR adds a list of disallowed subnets to the station config which are checked before marking the registration valid. By default the private subnets are included here. Ideally station operators will add the addresses of their stations when configuring during setup to prevent unauthorized connections to station operations. 
* Fix a few compile warnings in the rust detector portion of the station. 
* Add the source and destination addresses of the traffic to the zmq payload that is sent from the detector to the station so that it can be logged with the application information.

Add Config options for subnet filtering

---

Cargo.toml
application/config.toml
src/lib.rs
src/process_packet.rs

When stations perform liveness checks the connections from the stations to the phantom address picked up by the detector and registered as a potential connection. This creates a number of log lines and forces the station to attempt to handle the connections. To prevent this there is a list of source addresses to filter traffic out of the connection checks. This is currently hard coded and not easily configurable
Move the filter addresses to the station config and have each core parse the filter addresses during initialization. They probably don't need to be per core because they aren't unique and they aren't mutable, but that is how we currently track things. 
In this patch each core parses the station toml config once at initialization and only takes out the pices it needs (i.e. the …

Detector Address filtering

---

application/lib/registration.go
application/lib/registration_test.go
application/main.go

During the registration process a station may receive the same registration multiple times. Currently this results in the registration being fully processed each time it is received, including liveness testing. However it is entirely possible to do an early lookup and prevent the extra processing for registrations that are already valid  
To fix this I have added a `RegistrationExists` function to the registration manager which allows the station to do a lookup upon receiving a registration to check if the registration is already known. If the registration is already tracked the station short circuits the processing pipeline and returns. 
Based on the way that the registratiion manager tracks registrations, v4 and v6 registrations are tracked independently so adding to the count for each …

Early registration lookup in station tracking

---

application/lib/proxies.go
application/lib/registration.go
application/main.go
registration-api/main.go
src/flow_tracker.rs
src/lib.rs
sysconfig/conjure.conf

Conjure station by default log associate client IPs with connection checkpoints. This is not always desired behavior.
This PR adds an environment variable to the `conjure.conf` that is set during initialization in the detector, the station application, and the registration API. If set to true client IP addresses will be included in logs.  If the value is missing or set false client IP addresses will be excluded from logs.

Client IP Loggging

---

application/config.toml
application/lib/config.go
application/lib/proxies.go
application/lib/registration.go
application/main.go
registration-api/main.go

This handles a number of issues that were discovered spontaneously in production
1. go doesn't automatically clean up sockets on interrupt in `zmq_proxy`, which can cause the zmq_proxy thread to crash. This will cause the station to stop ingesting registrations, missing all connections
2. The liveness testing is turned up too high. This results in too many tcp sockets being used concurrently. 
3. Data race in registration tracking because of early tracking and lookup added in #63 
4. `too many files open` causing things to fail with locks, causing deadlock on golang station.
1. To fix the socket cleanup a defered close is added for the sockets in both directions. This seems to prevent the sockets ending up in a state where they fail to connect and crash the station. 
2.  The number of …

Prod Patches

---

application/lib/registration.go
application/main.go

Station application is blocking intermittently. It seems to be waiting on the lock for registration tracking.
The (almost certainly) longest duration lookup is the `removeOldRegistrations` function which has multiple steps and is required to iterate through the entire list of registrations. If we are storing a large number of registrations this means a linearly longer time that it holds the lock on registration tracking. 
To fix this I have made the removal of expired registrations modular wrt. the mutex. So now it takes a read lock to itemize and get a list of all expired registrations, then it takes a lock one by one to delete them. This means that the stations should never have to wait an extreme amount of time to get the lock to ingest a new registration. 
This PR adds two new …

Prod patch2

---

application/lib/zmq_proxy.go
application/lib/zmq_proxy_test.go

This PR attempts to fix the race condition caused by proxying to the same `pubSock` from multiple goroutines. It instead feeds all reads from each subscribe socket into one centralized goroutine to publish messages back out. I was able to reproduce the condition of the socket locking up when proxying from multiple goroutines concurrently, and have verified that centralizing the sends fixes that issue. I haven't been able to test this specific change since I took my test environment offline, though it's a fairly straightforward fan-in via a channel.

Fix ZMQ race condition from proxy

---

application/lib/registration.go

race condition caused by un-locked `totalRegistrations` count method. 
Add a wrapping function that can be accessed from outside the struct that locks before counting all registrations. Any functions using the private `totalRegistrations` function will not lock (potentially a second time causing deadlock). Any functions only using the public `TotalRegistrations`  function will lock preventing data race conditions. 
In the logs this occurred because of a call to `totalRegistrations` in `removeOldRegistrations`, which is a special case where we use the external functions to lock for piecewise progress so that the function doesn't hold a lock on the struct for long periods of time while cleaning up. 
```
Feb 10 14:29:03 conjure[9125]: ==================
Feb 10 14:29:03 conjure[9125]: [REG] …
```

Race Condition in Application Reg tracking.

---

src/sessions.rs

Session tracking doesn't explicitly drop the lock when managing sessions [here](https://github.com/refraction-networking/conjure/blob/dd2e1bcdb474b385d9251ed0495ea5fda8248c13/src/sessions.rs#L365). This isn't necessary a problem because locks are implicitly dropped when they fall out of scope. 
Explicitly drop the reference to the map so that we do not have to worry about revisiting this later. This is passing the test that triggers the conditional statement at line 354 (session exists).

Explicitly drop lock in Sessions.rs

---

.dockerignore
docker/Dockerfile
docker/README.md
docker/detector-entrypoint.sh
docker/docker-compose.yaml
docker/simple-entrypoint.sh
docker/start_zbalance_ipc.sh
docker/zbalance-entrypoint.sh

* Added multistage Dockerfile for each service (except registration)
* Added Readme with a quick start information
* Added detector-entrypoint.sh which includes routing and tun interface configuration (similar to on-reboot.sh)
* Added simple entrypoints for other services
* Added docker-compose.yaml with sample configuration and mandatory variables
Major difference is DNAT-ing to localhost instead of public IP by default and enabling net.ipv4.conf.all.route_localnet. This simplifies minimum required configuration.
All files (except .dockerignore) are in a separate directory so it should not have any impact on current deployment procedures.

Docker and Related

---

application/main.go

When a station receives a registration for a phantom in its phantom_blocklist, currently it is ignored (no liveness check, not shared with registration API, not added to local regManager).
This changes the behavior so that if we get a registration for a phantom in the phantom_blocklist, the registration is tracked, a liveness check is done, and it is shared with the registration API. We still do not add it to the local regManager, so this station won't pickup the connection (and our detector should still ignore it).
We want this because sometimes a station sees lots of decoys / registrations, and we want the central API to hear about them too, but we do not want that particular station to answer for those phantoms (e.g. they all go past another station).

Change phantom_blocklist behavior

---

INSTALL
src/lib.rs
src/process_packet.rs
stations/rockypika/erspan-pfring-hash.patch
sysconfig/conjure.conf
sysconfig/start_zbalance_ipc.sh
sysconfig/zbalance.service

The largest change here is the addition of a PARSE_GRE_OFFSET env variable that specifies how many bytes we should skip to get the Ether header (current stations this should be 0, but rockypika should be 42).
Other changes are mostly superficial:
- add an INSTALL instructions file
- add the rockypika / gre specific pfring patch in stations/rockypika
- update the zbalance systemd to run based off conjure variables (e.g. don't assume tapdance)
This is tested on rockypika (detector can see TLS packets with the GRE_OFFSET), but haven't tested the conjure-app there (no changes to application, though).

Build changes to get conjure working on rockypika

---

application/lib/proxies.go
application/lib/registration.go
application/lib/stats.go
application/main.go

Currently we just let connections/registrations post data and hope ELK can parse all that. But ELK is bad at tracking state transitions and counting, so this change adds a stats module that prints out once every (currently) 5 seconds.
Log lines look like:
`[STATS] 2021/03/20 03:19:10.705127 Conns: 1 cur 0 new 0 err Regs: 1 cur (0 local 1 API) 0 new 0 miss 0 err 0 dup LiveT: 0 valid 0 live Byte: 2124 up 2230336 down`
This tracks number of current/new(since last 5 seconds) connections, registrations (and their source), registration errors (miss == connection with no corresponding reg, err = generic other error, dup == we saw this reg before and ignored it), liveness test results (valid vs live), and bytes.
Currently, bytes only gets updated when a connection ends, but I have a second PR …

Update stats in conjure-app

---

registration-api/api_test.go
registration-api/main.go

Currently stations require inclusion of client addresses in registration tracking to limit the interference with non-affiliated traffic. However, the registration API was drawing this directly from the requests remote source address, or attempting to use the `X-Forwarded-For` header as a whole as an address. This breaks things when a registration received over the registration API is sent through a proxy. 
I have added parsing for extended X-Forwarded-For headers to allow proxy API registration in ipv4.
Note: In the future we may want to add support for the `True-Client-Ip` header, but this is sufficient for now.

Handle client addreses in proxied X-Forwarded-For headers

---

application/lib/stats.go

The current stats track API and DetectorPrescan registration sources as the same thing. Now that we are rolling out some API registrations it would be nice to be able to see that count accurately
Separate out the registration sources to track all individually. Will require an update to the log parsing systems.

Disentangle API registration counts

---

application/lib/registration.go

The timeout currently hard-coded for garbage collection of registrations is fixed at a short time period. This doesn't allow clients to cache and re-use registrations for very long.  
Update hard-coded default registration tracking timeout from 2 mins to 6 hrs. This is an intermediary step between no caching and caching with aggressive timeouts as described in #83

Update default registration timeout to support registration caching

---

src/signalling.rs

Rust version 1.52.1 considers inner attributes as unstable and throws an error during compile. Protoc rust generation currently uses inner attributes in the generated code. 
```log
error: custom inner attributes are unstable
--> src/signalling.rs:9:4
|
9 | #![rustfmt::skip]
|    ^^^^^^^^^^^^^
|
= note: `#[deny(soft_unstable)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #64266 <https://github.com/rust-lang/rust/issues/64266>
error: aborting due to previous error
error: could not compile `rust_dark_decoy`
```
To fix this for now we manually remove inner attribute set by protoc which causes the error in `cargo build` with rust 1.52.1. This is a …

Protobuf rust inner attributes error with rust-1.52.1

---

application/lib/registration.go
application/lib/stats.go

The station application was miscouting both activeRegistrations and
newErrConns. This PR fixes both issues.
* The activeRegistrations we being incremented only for valid
registrations, but decremented for all retired registrations. This is
fixed by checking the validity when calling ExpireReg(...).
* newErrorConns wsa increasing monotonically because it was never added
to Reset() despite being a periodic metric.

Address mis-counts in stations application metrics

---

docker/.dockerignore
docker/detector-entrypoint.sh
docker/docker-compose.yaml
docker/start_zbalance_ipc.sh
docker/zbalance-entrypoint.sh

Update build and run process to expect config files in specific locations. This forces environments to configure parameters that will be used locally. Also fixes an issue where `CJ_IFACE` string containing multiple iface names is treated as one iface by `zbalance-entrypoint.sh`.
* Station Config is stored in `/etc/conjure/...` which docker maps to volumes in appropriate locations for each service (i.e `/etc/conjure/conjure.conf -> /opt/conjure/sysconfig/conjure.conf`). 
* `CJ_IFACE` (set in `/etc/conjure/conjure.conf`) can support multiple ifaces (i.e. `CJ_IFACE=enp5s0f0,enp5s0f1,...`).
* `zbalance-entrypoint.sh` checks for ZC support in `/proc/net/pf_ring/dev/${iface}/info` for each individually.

Docker support local config files & multiple PF_RING ifacs.

---

src/sessions.rs

The cargo clippy linter has added a new lint checking for the use of `to_string()` where the `Display` trait is already implemented allowing for simpler code. This is throwing a warning in a few places in `src/sessions.rs` causing the lint GH action to fail. 
This PR fixes those small warnings, allowing the GH action to pass for the latest version of clippy.

Fix clippy lint warnings for rust 1.58

---

registration-api/api_test.go
registration-api/main.go

* remove potential nil pointer derefence in protobuf struct traversal
* remove non-specific debug log lines
* Add test for `parseClientConf()`

Bug fixes in ClientConf API delivery via Bidirectional Registrar

---

application/lib/config.go
application/lib/config_test.go
application/lib/registration.go
application/main.go

Clients that register using covert addresses that are dissallowed at a particular station will have their registration ignored and their IP logged. This allows us to keep an eye on clients who are attempting to abuse the station.

Log Misbehaving Client IPs

---

sysconfig/zbalance.service

I'm going through setting up a development environment and found an inconsistency in the zbalance service file. The service loads correctly when the path to `start_zbalance_ipc.sh` is changed to reflect it's relative location in the conjure  repository.

Correct path to start_zbalance_ipc.sh script

---

registration-api/api_test.go
registration-api/main.go

The bidirectional API is supposed to include an updated clientconfig if available, however the check currently includes the clientconf for connections that have the same generation number, using many more bytes than required for most registrations. 
This PR fixes this by changing the generation number check to ensure that equal generation numbers are not served the latest clientconfig (which they already have).

bidirectional api only include clientconf for gen less than current

---

application/lib/test/phantom_subnets_min.toml
application/transports/wrapping/internal/tests/tests.go
application/transports/wrapping/obfs4/obfs4.go
application/transports/wrapping/obfs4/obfs4_test.go

Fix for unconditional return in obfs4 WrapConnection - move checks on proper data length earlier in the function and continue through loop when the MAC mark that we are looking for is not found.
The fix(es) applied in this PR relates to #132 as we add a temporary fix that creates an [ioutil.tempdir](https://pkg.go.dev/io/ioutil#TempDir) for each obfs4 session ensuring separation of state. However this is probably not a good long-term fix as file descriptor limitations might cause issues, also we probably don't need any of the files to begin with.
closes #128 
relates to #132
**obfs4**
* move mark len check proper locations 
* too short check up front
* not found, but not past max at end for retry
* mark not found w/ one reg, continue to next instead of return
* use tempdir instead of …

bug fixes for obfs4 only. test will fail due to #133

---

.github/workflows/build.yml
.github/workflows/golang.yml
application/config.toml
application/lib/config.go
application/lib/config_test.go
application/main.go
libtapdance/elligator2.c

This PR addresses an SSRF issue by resolving all covert domains before applying the blocklist filtering.  Resolved addresses are  then DNS pinned to registrations to prevent DNS rebinding attacks. 
Along with this fix we comment client code for generating tag information that is unused in conjure (client ed25519 tag generation is done in golang). In general we consider memory exfiltration attacks against clients out of scope.

Blocklist fix via DNS pinning

---

application/lib/phantom_selector.go
application/lib/phantom_selector_test.go

**Problem**
Our current (V1) phantom selection algorithm depends on `math/rand` and has a bug involving Varints: we attempt to parse the 256-bit secret as a Varint to get a 4-byte integer, which we seed `math/rand` with. Unfortunately, half of the secrets we would pass in would have a leading 0 bit, causing the Varint parsing to return only the single byte (in the range -64 to 63). As a result, half the time we will only select from a set of 128 phantom IPs.
An example test `TestDuplicates` is now in phantom_selector_test.go, and if one edits the ClientLibVersion to be 1, it will detect the problem. Notice the leading bit of both seeds are 0, and the byte is the same (0x30) between the two tests that demonstrate generating the same IPv6 address.
```
--- FAIL: TestDuplicates (0.00s) …
```

Fix phantom selection algorithm

---

application/lib/registration.go
application/lib/registration_config_test.go
application/lib/test/phantom_subnets_update.toml
application/main.go

Use the SIGHUP signal to indicate to the station to re-parse and apply changes to the configs in production without a shutdown.

Phantom reload

---

application/lib/registration_ingest.go

The default ingest buffer capacity should be small. Allowing registrations to queue for too long hurts the health of the station overall during and following a burst of registrations. It must be possible to handle any registrations that do make it into the buffer in a reasonable amount of time, otherwise the registrations should be dropped.

Adjust default ingest buffer channel capacity

---

cmd/registration-server/main.go
pkg/apiregserver/apiregserver.go
pkg/dnsregserver/dnsregserver.go
pkg/regprocessor/regprocessor.go
sysconfig/conjure-app.service
sysconfig/conjure-registration-server.service

clientconf reload for bidirectional API registrar and phantom subnet reload for processor
This is not intended to reload all settings and rebuild the entire server, just the key elements that we would want to reload regularly without restarting the services.

Reload Handling for combined Reg Server

---

pkg/apiregserver/apiregserver.go
pkg/apiregserver/apiregserver_test.go

Our current `X-Forwarded-For` (XFF) handling is not properly implemented to get the last client IP address included by proxy hops. 
Update the handling of XFF (and potentially other client IP) headers in the API registrar.  
For reference: 
- https://adam-p.ca/blog/2022/03/x-forwarded-for/
Changes:
- `parseIP` returns  `net.IP` instead of `*net.IP` - downstream calls can handle pass by reference if needed.
- `getRemoteAddr` returns `net.IP` (or `nil`) instead of `string` - all uses need a parsed IP anyways, also allows a quick failure
-  `getRemoteAddr` updated to follow better practices for parsing and handling real client IP headers
- `TestAPIGetClientAddr` updated to reflect new behavior

X-Forwarded-For Handling

---

application/lib/registration_stats.go

copy-paste error in mutex name lead to station crash
``` log
Nov 16 12:58:17 decoy-tap systemd[1]: conjure-app.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 16 12:58:17 decoy-tap conjure[1610467]:         /home/jmwample/conjure/application/lib/registration_ingest.go:58 +0x170
Nov 16 12:58:17 decoy-tap conjure[1610467]: created by github.com/refraction-networking/conjure/application/lib.(*RegistrationManager).HandleRegUpdates
Nov 16 12:58:17 decoy-tap conjure[1610467]:         /home/jmwample/conjure/application/lib/registration_ingest.go:111 +0x214
Nov 16 12:58:17 decoy-tap conjure[1610467]: github.com/refraction-networking/conjure/application/lib.(*RegistrationManager).startIngestThread(0xc000234340, {0x9f6ad8, 0xc000234380}, 0xc000034240, 0x0?)
Nov 16 12:58:17 …
```

Registation ingest stats crash

---

application/transports/wrapping/obfs4/obfs4.go
application/transports/wrapping/obfs4/obfs4_test.go
go.mod
go.sum

Creates a _somewhat_ more permanent fix for #132. This makes use of a fix that I implemented in a fork of the obfs4 repo which treats an empty statedir string as `"Do NOT use local state"` rather than treating it as `"./"`.  To me this seems like a better and more explicit way to handle state (or lack there-of). For now I have added a PR against the upstream obfs4 repository https://github.com/Yawning/obfs4/pull/35 and added a `replace` in the `go.mod` to use my fork in the hopes that it  will be accepted soon at which time we can just remove the `replace`. Alternatively if that PR leads to some other fix we can support it here in a future PR.
To re-iterate the problem: We use independent keys for each session making a connection using the obfs4 transport with the keys derived from the …

Obfs4 stateDir handling 

---

.github/workflows/build.yml
.github/workflows/golang.yml
.github/workflows/rust.yml

It seems like all `v2` actions ran using node12 which lost support in the fall. the github actions warn that all actions should be updated to use node16. This seems to mean that all actions need updated to `v3`.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Github Actions update

---

.github/workflows/golang.yml
application/config.toml
application/geoip/empty.go
application/geoip/geoip.go
application/geoip/geoip_test.go
application/lib/config_test.go
application/lib/proxies.go
application/lib/proxies_test.go
application/lib/registration.go
application/lib/registration_config.go
application/lib/registration_ingest.go
go.mod
go.sum

In order to better understand the state of proxy tunnels this PR adds geoip information to event stats for specific events without logging client IP addresses. 
Client Geoip info (country code and ASN) has been added to the Proxy tunnel close log messages and the registration expire message. The registration expire message has been demoted to `debug` error level because it is not a very useful metric. 
Geoip lookup is implemented using MaxMind ASN and Country databases and config parameters for the paths to the databases are now available in the `application/config.toml`. If no path is provided then an `EmptyDatabase` is used which always returns `0` for ASN and `""` for countrycode which should be ommitted from the json log message. The paths are configured to be reloadable with the …

Event stats with GeoIP info

---

sysconfig/geoipupdate

Add geoip update script for `/etc/cron.weekly/` that runs geoipupdate then sends the reload signal to the conjure station.

Add Geoip Update for cron

---

application/lib/proxies.go

timeouts assigned to both covert and client conns for stats tracking purposes because there is effectively a race condition determining which of the two linked conns will timeout first. We count this as a timeout for both connections as golang cant actually tell us which side is still live / retransmitting and such.  
From golang's perspective silence is bidirectional since we don't see acks / retransmits

Proxy timeout error tracking

---

application/transports/obfuscate.go
application/transports/obfuscate_test.go
application/transports/transports.go

add optional methods to obfuscate session hmacID using ECDHE+AES
This is beneficial because currently when a registration is used more than once the same hmac-id will be sent for the prefix transport for all connection. This will be useful for future transport implementation.

Add Connection Tag Obfuscation Options

---

pkg/regprocessor/auth_test.go
pkg/regprocessor/regprocessor.go
pkg/regprocessor/regprocessor_test.go
src/lib.rs

This PR adds a regression test for the registration server to authenticate ZMQ connections. It is critical that this test is passing indicating that ZMQ authentication is enabled and pre-shared keys are required to connect.

Zmq Auth Regression test

---

application/transports/anypb_nourl.go
application/transports/anypb_nourl_test.go
application/transports/wrapping/min/min.go
application/transports/wrapping/obfs4/obfs4.go

Protobuf changes in refraction-networking/gotapdance#110 made registration payload too large for the DNS registrar to handle. In refraction-networking/gotapdance#108 we use a workaround by removing the `TypeUrl` in the added `TransportParams` anypb, since we already know the type for each transport. Add the `TypeUrl` back upon receiving the `TransportParams` for anypb to unmarshal.

Optimize registration payload size for DNS registrar

---

util/captool/Cargo.toml
util/captool/src/main.rs
util/captool/src/packet_handler.rs

This PR adds a timeout option to terminate captures. This is helpful if running the captures automatically using something like cron.

Anonymized Capture Tool Timeout

---

on-reboot.sh

This PR adds a simple sysctl check to on-reboot for conntrack timeout. For now I have only tested this on 20.04 and 22.04 for the default sysctl values relating to TCP timeout. 
If the tcp retransmission variables have been modified this may not work properly and you risk allowing outgoing packets with the real station IP instead of the spoofed phantom IP. A future iteration could directly access the tcp retransmission variables to ensure that there will be no race between retransmission and GC in the conntrack tables, but for now this is good enough (and I am not sure I understand the TCP failure flow where the client dissapears well enough to calculate this properly).

Add Conntrack Timeout to `on-reboot.sh`

---

Cargo.toml
rust_util.c
src/lib.rs

This PR fixes a serde usage issue that was breaking compile for serde `v1.0.130`  as well as a compile warning that has been around for a while about `strncpy` bounds.

Maintenance updates

---

.gitignore
docker/Dockerfile
docker/docker-compose.yaml
on-reboot.sh
sysconfig/conjure-reg.service
sysconfig/zbalance.service

* fix error in `conjure-reg.service` around paths
* update `on-reboot.sh` to not infinitely add iptables rules.
* use explicitly named rule chains
* if you run `on-reboot.sh` and the chain already exists it will delete it and make it anew
* updated `zbalance.service` to run `on-reboot.sh` as an `ExecPrestart` to ensure that env is set up even on reboot.

Infrastructure fixes

---

application/lib/proxies.go
application/lib/registration.go
application/lib/registration_ingest.go
application/lib/transports.go
application/lib/transports_mock.go
application/transports/wrapping/internal/tests/tests.go
application/transports/wrapping/min/client.go
application/transports/wrapping/min/min.go
application/transports/wrapping/min/min_test.go
application/transports/wrapping/obfs4/client.go
application/transports/wrapping/obfs4/obfs4.go
application/transports/wrapping/obfs4/obfs4_test.go
application/transports/wrapping/prefix/client.go
application/transports/wrapping/prefix/prefix.go
application/transports/wrapping/prefix/prefix_test.go

This is a follow-on to #165 that cleans up several things that were missed, like 
* stats logging w/ selective parameters
* Prefix compatibility with `transports.NewWithParams()`
* Client option to use a random prefix
client side changes
https://github.com/refraction-networking/gotapdance/pull/121
https://github.com/refraction-networking/gotapdance/pull/124

Prefix Transport debugging fixes

---

application/conns.go
application/conns_test.go
application/lib/proxies.go
application/lib/proxies_test.go
application/lib/stats.go

One of the main stations crashed overnight seeminlgly due to thread starvation in the `proxy.halfPipe()` function. In the crash logs in syslog it says: `oroutine 6_933_001 [semacquire, 4 minutes]:` which makes me things that there may have been ~7 million goroutines running.
```syslog
Jun 29 00:13:14 : conjure-app.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 29 00:13:13 :         /opt/conjure/application/conns.go:66 +0x2fb
Jun 29 00:13:13 : created by main.(*connManager).acceptConnections
Jun 29 00:13:13 :         /opt/conjure/application/conns.go:112 +0x2f2
Jun 29 00:13:13 : main.(*connManager).handleNewConn(0xc025e3da40?, 0x0?, 0xc024efcdd8)
Jun 29 00:13:13 :         /opt/conjure/application/conns.go:327 +0x1bb9
Jun 29 00:13:13 : …
```

Crash Debug 

---

docker/docker-compose.yaml
src/process_packet.rs
src/sessions.rs
sysconfig/conjure.conf

Quick fixes that resolve small issues
- change to `sysconfig/conjure.conf` to use `ip` instead of ifconfig, which is not guaranteed to be installed on newer ubuntu versions
- change docker-compose to name containers and use those names when logging to journald
- remove two persistent and uninformative log lines from detector logging.

minor ops fixes and convenience changes

---

cmd/application/conns.go
cmd/application/conns_test.go

All transition functions have been adjsuted to check if the connection is IPv4 or IPv6 and update the corresponding statsCount object. Printing has been updated to print 2 lines (IPv4 and IPv6) for each conn-stats and conn-stats-verbose. Tests have been updated to work with changes.

IPv4 vs IPv6 State Tracking

---

cmd/application/conns.go

make mocking conns slightly easier for `handleNewTCPConn()`
If using a non-IP based `net.Conn` you will need to wrap and mock / override `RemoteAddr()` to make sure it does return a net.IP.
```go
remoteIP := getRemoteAsIP(clientConn)
if remoteIP == nil {
// Socket returned non-IP Remote Address - we can't really use that. If testing w/ pipe try
// wrapping with struct to provide mock RemoteAddr which return a real IP address.
return
}
```

Use switch with default for RemoteAddr parsing

---

docker/Dockerfile
prereqs_once.sh

The golang installer in `prereqs_once.sh` was breaking docker builds. This PR provides a solution.
note: this is probably not the best solution, in theory we should be using the golang docker image as a multi-stage target to build with `GOOS=linux`. However, I have never messed with that before, so for now this does the job.

Golang Install in prereqs fix

---

.gitignore
Makefile

Recursively call make clean on libtapdance directory and make sure to use -r with rm to properly remove $EXE_DIR
Update .gitignore for new executable paths

Update clean target for Makefile and .gitignore

---

pkg/transports/anypb_nourl.go
pkg/transports/anypb_nourl_test.go

Fix a potential nil dereference in parameter parsing with test
```
--- FAIL: TestEmpty (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x912ecc]
goroutine 19 [running]:
testing.tRunner.func1.2({0x95a760, 0xd06e10})
/usr/local/go/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1548 +0x630
panic({0x95a760?, 0xd06e10?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/refraction-networking/conjure/pkg/transports.UnmarshalAnypbTo(0x0, {0xa63120, 0xc00015a370})
/conjure/pkg/transports/anypb_nourl.go:21 +0x10c …
```

Avoid nil pointer deref

---

Cargo.lock
Cargo.toml
src/lib.rs
src/logging.rs

The dependency on the chrono crate in `src/logging.rs` for `Local::Now()` which returns a `DateTime` and then the subsequent formatting mean that we import chrono. On some execution paths chrono calls `libc::localtime_r` which can crash. I don't think that we run that execution path, but it isn't impossible.
Hopefully updating to 0.4.27 fixes this. Chrono is a widely used datetime crate in rust.
https://github.com/refraction-networking/conjure/security/dependabot/8

Update rust chrono dep to (maybe) fix dependency alert

---

src/logging.rs

PR #220  added an unhandled unwrap for the function call `time::OffsetDateTime::now_local()`
Turns out this can panic unexpectedly. This adds a more reliable utc fallback.

Unhandled Panic from `time::OffsetDateTime::now_local()`

---

src/logging.rs

The changes to the DateTime library used by the detector made in #221 and #220 resulted in a minor change to the actual value that gets logged (missing sign on offset hour value). This PR fixes this making our log timestamps using the `time` crate are now parse-able by the logstash grok pattern that we used for the timestamp of `chrono`.
P.S. Timestamps and time libraries are a huge hassle

Detector log timestamp format fix

---

pkg/regserver/regprocessor/regprocessor.go
pkg/regserver/regprocessor/regprocessor_test.go
pkg/station/lib/phantom_selector.go
pkg/station/lib/phantom_selector_test.go
pkg/station/lib/registration_ingest.go
pkg/station/lib/registration_ingest_test.go

Make types usable outside of the package where `Select()` is used. 
Note: Some of the `TestPhantoms...` test functions are not passing seemingly because of the changes to the phantom selection. We need to make sure this is going to be backwards compatible so that the phantoms that older clients using unidirectional registrars select still match the ones we select for them.

phantom Select w/ random port indicated

---

pkg/regserver/regprocessor/regprocessor.go
pkg/regserver/regprocessor/regprocessor_test.go
pkg/station/lib/phantom_selector.go
pkg/station/lib/phantom_selector_test.go
pkg/station/lib/phantoms.go
pkg/station/lib/phantoms_test.go
pkg/station/lib/registration_ingest.go
pkg/station/lib/registration_ingest_test.go
pkg/station/lib/test/phantom_subnets.toml

Follow up to #208 so that station side also checks port randomization instead of just reading from registration.

Check subnet port randomization support on station side

---

pkg/transports/wrapping/prefix/client.go
pkg/transports/wrapping/prefix/prefix_test.go

Multiple fixes to errors introduced in `v0.7.X`.
- resulted in prefix and tag not being written at all.

Bug Hunting in v0.7.x

---

Cargo.lock
Cargo.toml

Solution for:
https://github.com/refraction-networking/conjure/security/dependabot/9

Update aes-gcm dependency to satisfy a dependabot alert

---

pkg/regserver/regprocessor/regprocessor.go

This PR fixes a small bookkeeping error that labels all API registrations as API, whether they are bidirectional or not. This hinders some of the performance stats tracking.
The simple fix was to remove a line that relabels bidirectional API registrations as plain API.

API Registration Source Fix

---

Cargo.toml

the pattern match for rust `Cargo.toml` dependencies  allows use of protobuf `3.3.0` which has breaking API changes.
`3.2` matches `>=  3.2.0` up to `< 4.0.0` -- however version `3.3.0` has breaking API changes so using this dependency wont work.
instead match `3.2.*` which is anything between `>=3.2.0` and `< 3.3.0`

Rust protobuf dependency

---

go.mod
go.sum
internal/port_integration_test.go
internal/test_assets/phantom_subnets.toml
internal/transport_integration_test.go
pkg/core/interfaces/interfaces.go
pkg/transports/connecting/dtls/client.go
pkg/transports/wrapping/min/client.go
pkg/transports/wrapping/obfs4/client.go
pkg/transports/wrapping/prefix/client.go
pkg/transports/wrapping/prefix/prefix_test.go

1. undo unnecessary change to the internal `Transport` interface and ensure all subnets not supporting port randomization use the default port
2. Prefix transport selects the incorrect port for the chosen prefix id
In general I have been mentally conflating things that should generally be independent wrt. port randomization, the prefix transport, and the transport interface. For starters the prefix transport "port randomization" is not the same as the subnets "not supporting port randomization". The prefix transport (and really all of the transports that have their own "Randomize Destination Port" parameter) indicate user preferences indicated by the dialer. This was originally used for the min and obfs4 transports to enable port randomization. For the prefix transport using this …

Port Randomization follow-up fixes

---

pkg/registrars/decoy-registrar/decoy-registrar_test.go
pkg/registrars/decoy-registrar/utils.go
pkg/registrars/registration/api-registrar_test.go

There's currently an assets.go in both this repo and the gotapdance one. The decoy-registrar (now living in this conjure repo) relies heavily on the conjure-based assets, which means the gotapdance client should also use that one (otherwise, any local changes the client makes to assets will be ignored when it uses the decoy-registrar).
However, there are still some vestigial references in this conjure repository for gotapdance assets. This PR fixes that, and exclusively uses the assets provided by conjure (`github.com/refraction-networking/conjure/pkg/client/assets`).

Switch to using conjure-only assets to stop circular dependency

---

scripts/start_zbalance_ipc.sh

It seems like running zbalance in daemon mode using the `-d` option does not do what I thought it would do. However, the `-z` option is the [proc_stats_only option](https://github.com/ntop/PF_RING/blob/434ff5b2d6c2e701aa9429f5266337c99764a541/userland/examples_zc/zbalance_ipc.c#L1193) which reduces the lines logged by zbalance, which we are not currently using anyways as we have a packet counter in the detector.

start zbalance as daemon with -d seems to break things -> switch to -z

---

go.mod
go.sum

https://github.com/refraction-networking/conjure/security/dependabot/10
Update `golang.org/x/net` dependency requirement to `v0.17.0`

Fix dependabot warning #10 related golang.org/x/net

---

go.mod
go.sum
pkg/station/lib/registration.go
pkg/station/lib/registration_ingest.go
pkg/station/lib/registration_test.go

In the registration ingest pipeline we check if the incoming registration has been seen before, as it is possible with certain registrars that more than one registration are seen for a single connection. 
In order to do so we track all seen registrations in the registration manager and check against the state when a new registration is received. 
---
**Issue:** By necessity the ingest pipeline is multi-threaded. This means that two registrations can be in the ingest pipeline simultaneously. The Time-of-Check to Time-of-Use error happens because there the step that checks whether a registration has been seen before and the step that adds the registration to the registration managers state are independent. This means that registrations being ingested in parallel could both pass the …

Registration ingest ToC-ToU race wasting resources 

---

pkg/dtls/sctpconn.go

dtls.SCTPConn is the net.Conn returned from gotapdance.Dial for the Conjure protocol with the DTLS transport. Callers may expect that net.Conn to behave as a TCP-like byte stream, and not an SCTP message stream, and these changes accomodate that. These changes should also be appropriate for use of dtls.SCTPConn on the station side.
- Skip 0-byte writes
- Buffer reads, allowing the caller to read smaller amounts of bytes without hitting the "short buffer" error
- Add write flow control to avoid possibly unbounded outbound packet buffering

Enhancements for dtls.SCTPConn

---

pkg/dtls/heartbeat.go
pkg/dtls/heartbeat_test.go
pkg/dtls/sctpconn.go
pkg/dtls/server_test.go

Check if an insufficient buffer is used in hbConn.Read().

Fix heartbeat read buffer bug

---

pkg/station/lib/proxies.go
pkg/station/lib/proxies_test.go
scripts/install_pfring.sh

It is somehow possible for the proxy to make an out of bounds access in the halfpipe slice creation. It is not clear how this is possible since we are calling read with a fixed size buffer, but the issue seems to have occurred on several stations independently.
```log
12:44:51 conjure: panic: runtime error: slice bounds out of range [:32804] with capacity 32768
12:44:51 conjure: goroutine 192061459 [running]:
12:44:51 conjure: github.com/refraction-networking/conjure/pkg/station/lib.halfPipe({0xbcdb28, 0xc003cac040}, {0xbcd618, 0xc0164223c0}, 0xc009744520, 0xc000246b20, {0xc01682a8b8, 0x13}, 0xc005a89680)
12:44:51 conjure:         /opt/conjure/conjure/pkg/station/lib/proxies.go:158 +0x870
12:44:51 conjure: created by github.com/refraction-networking/conjure/pkg/station/lib.Proxy in …
```

Alternate fix for oob slice creation in proxy halfpipe

---

pkg/transports/wrapping/prefix/client.go
pkg/transports/wrapping/prefix/prefix_test.go

use client specified flush policy if set over bidirectional registrar provided flush policy

Use client Flush parameter always if set

---

.github/workflows/golang.yml
go.mod
go.sum
pkg/dtls/heartbeat_test.go
pkg/dtls/seedtocert.go

To keep compatibility with go 1.19 and in future versions.

Use ECDSALegacy to generate keys

---

pkg/dtls/listener.go
pkg/dtls/seedtocert.go

- Add salt when creating hkdf rand reader from conjure seed
- Uncomment server cert so that client and server certs are different
- Use `crypto/rand.Reader` instead of reader from conjure seed for signing since signature does not have to be the same

Fix issues with cert generation

---

pkg/transports/connecting/dtls/client.go

For DTLS, concurrently dial and listen and use which ever completes the handshake first, instead of waiting 5 seconds for listen and then falling back to dial.

Concurrently dial and listen dtls

---

pkg/dtls/listener.go

The DTLS listener can run into deadlock [here](https://github.com/refraction-networking/conjure/blob/master/pkg/dtls/listener.go#L65-L74) due to being stuck at `acceptCh <- newDTLSConn` and not releasing the mutex.

Fix deadlock by buffering acceptCh channel

---

pkg/station/lib/proxies.go

Increase proxy stall timeout

---

util/captool/src/main.rs
util/captool/src/packet_handler.rs

./captool ...... --except "subnets_list"
An optional arg to allow for the exclusion of certain subnets from traffic capturing. This is useful when trying to avoid capturing station-covert flows when the station IP is within the target subnets specified by -t arg.

Adding a new option to captool to exclude subnets traffic from being captured

---

pkg/dtls/heartbeat.go

Add timer.Stop() to prevent dangling timers on hbConn/hbClient closure.

Prevent dangling timers

---

cmd/application/main.go
pkg/dtls/dial.go
pkg/dtls/goroutine_leak_test.go
pkg/dtls/heartbeat.go
pkg/dtls/listener.go
pkg/dtls/listener_test.go
pkg/dtls/server_test.go
pkg/transports/connecting/dtls/dtls.go
pkg/transports/connecting/dtls/dtls_test.go

Fix goroutine leaks unaddressed by #265 and add more tests for goroutine leak.

Fix and test goroutine leak

---

pkg/station/lib/registration_ingest.go

Instead of having the station derive the phantom IP for a given bidirectional registration that the station is informed about, let the station apply the IP it receives from the reg server (inside the reg response).
This allows clients to dial phantoms that are not necessarily in the ClientConf subnets, given that they registered using the bidirectional api.

Apply phantom IP overrides from the reg response

---

cmd/registration-server/main.go
cmd/registration-server/reg_config.toml
pkg/regserver/regprocessor/auth_test.go
pkg/regserver/regprocessor/regprocessor.go

This PR allows for overriding v4 phantom addresses during the bidi registrations (not overriding transport choices). Operators can specify the desired subnet overrides in the reg_config.toml file in the reg server. A new template for reg_config.toml is updated.

Support for experimental reg overrides

---

pkg/registrars/registration/api-registrar.go
pkg/regserver/regprocessor/regprocessor.go
pkg/regserver/regprocessor/regprocessor_test.go
src/elligator.rs

This change adds an IP field to bidirectional API registration requests and prioritizes this field, if it exists, over the station-determined remote address. Clients can use STUN to determine their public IP address.
This feature is particularly useful for domain-fronted connections over CDNs that mask the client IP for privacy reasons. Closes https://github.com/refraction-networking/conjure/issues/286
The one thing I wasn't sure about was the purpose of the condition that I removed from regprocessor.go:
```golang
c2sPayload.GetRegistrationSource() == regMethod
```
I assume this is here for some backwards compatability reasons. I couldn't see a reason to not remove it, but I might have missed something.

Allow client to send public IP in bdapi request
